name: Build & Release WSC Rule Trigger

on:
  workflow_dispatch:  # manually trigger from GitHub Actions tab

jobs:
  build:
    name: Build for Windows & macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # ✅ secure token for electron-builder

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build
          path: dist/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: Windows-build
          path: dist/windows

      - name: Download macOS build
        uses: actions/download-artifact@v4
        with:
          name: macOS-build
          path: dist/macos

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "WSC Rule Trigger v${{ github.run_number }}"
          files: |
            dist/windows/**
            dist/macos/**
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # ✅ same secure token
